//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Evaluations')
export class EvaluationsEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('integer', { nullable: true })
  reviewId: number;

  @Column('integer', { nullable: true })
  employeeId: number;

  @Column('date', { nullable: true })
  periodStart: Date;

  @Column('date', { nullable: true })
  periodEnd: Date;

  @Column('text', { nullable: true })
  goalsObjectives: string;

  @Column('text', { nullable: true })
  achievements: string;

  @Column('text', { nullable: true })
  improvementAreas: string;

  @Column('text', { nullable: true })
  feedbackFromSupervisor: string;

  @Column('integer', { nullable: true })
  overallRating: number;

  @Column('text', { nullable: true })
  recommendations: string;
}
