//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const EmployeesTitle = () => {
  const record = useRecordContext();
  return <span>Employees {record ? `"${record.firstName}"` : ''}</span>;
};

export const EmployeesList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="employeeId" />
      <TextField source="firstName" />
      <TextField source="lastName" />
      <TextField source="middleName" />
      <DateField source="dateOfBirth" />
      <TextField source="gender" />
      <TextField source="nationality" />
      <TextField source="maritalStatus" />
      <TextField source="contactInformation" />
      <TextField source="address" />
      <TextField source="department" />
      <TextField source="position" />
      <TextField source="manager" />
      <TextField source="employmentType" />
      <DateField source="startDate" />
      <DateField source="endDate" />
      <NumberField source="salaryInformation" />
      <ImageField source="profilePicture" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const EmployeesEdit = () => (
  <Edit title={<EmployeesTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="employeeId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="firstName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="lastName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="middleName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="nationality" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="maritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="contactInformation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="department" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="position" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="manager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="employmentType" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="salaryInformation" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="profilePicture" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const EmployeesCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="employeeId" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="firstName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="lastName" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="middleName" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="dateOfBirth" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="gender" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="nationality" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="maritalStatus" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="contactInformation" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="address" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="department" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="position" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="manager" />
        </Grid>
        <Grid item xs={4}>
          <TextInput source="employmentType" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="startDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="endDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="salaryInformation" />
        </Grid>
        <Grid item xs={4}>
          <ImageInput source="profilePicture" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
