//Source code generated by AppGPT (www.appgpt.tech)
import {
  Datagrid,
  List,
  EditButton,
  Edit,
  SimpleForm,
  Create,
  SelectColumnsButton,
  DatagridConfigurable,
  TopToolbar,
  CreateButton,
  ExportButton,
  FilterButton,
  //Field controls
  BooleanField,
  DateField,
  EmailField,
  ImageField,
  NumberField,
  ReferenceField,
  TextField,
  UrlField,
  //Input controls
  BooleanInput,
  DateInput,
  EmailInput,
  ImageInput,
  NumberInput,
  ReferenceInput,
  TextInput,
  UrlInput,
  PasswordInput,
} from 'react-admin';
import { useRecordContext } from 'react-admin';
import { Grid } from '@mui/material';
const ReadOnlyPasswordField = ({ record, source }) => {
  // You can customize the way you display the password here, e.g., mask it with asterisks
  const maskedPassword = '********';

  return <span>{maskedPassword}</span>;
};
const ListActions = () => (
  <TopToolbar>
    <FilterButton />
    <CreateButton />
    <ExportButton />
    <SelectColumnsButton />
  </TopToolbar>
);
const PayrollTitle = () => {
  const record = useRecordContext();
  return <span>Payroll {record ? `"${record.payrollId}"` : ''}</span>;
};

export const PayrollList = () => (
  <List actions={<ListActions />} filters={ResourceFilters}>
    <DatagridConfigurable>
      <NumberField source="payrollId" />
      <ReferenceField source="employeeId" reference="employees" />
      <DateField source="periodStartDate" />
      <DateField source="periodEndDate" />
      <NumberField source="grossSalary" />
      <NumberField source="deductions" />
      <NumberField source="netSalary" />
      <DateField source="payDate" />
      <NumberField source="overtimeHours" />
      <NumberField source="overtimePay" />
      <EditButton />
    </DatagridConfigurable>
  </List>
);

export const PayrollEdit = () => (
  <Edit title={<PayrollTitle />}>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="payrollId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="employeeId" reference="employees" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="periodStartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="periodEndDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="grossSalary" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="deductions" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="netSalary" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="payDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="overtimeHours" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="overtimePay" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Edit>
);

export const PayrollCreate = () => (
  <Create>
    <SimpleForm>
      <Grid container rowSpacing={1} columnSpacing={{ xs: 1, sm: 2, md: 5 }}>
        <Grid item xs={4}>
          <NumberInput source="payrollId" />
        </Grid>
        <Grid item xs={4}>
          <ReferenceInput source="employeeId" reference="employees" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="periodStartDate" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="periodEndDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="grossSalary" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="deductions" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="netSalary" />
        </Grid>
        <Grid item xs={4}>
          <DateInput source="payDate" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="overtimeHours" />
        </Grid>
        <Grid item xs={4}>
          <NumberInput source="overtimePay" />
        </Grid>
      </Grid>
    </SimpleForm>
  </Create>
);

const ResourceFilters = [
  <TextInput source="q" label="Search" alwaysOn />,
  ,
  <ReferenceInput
    source="employeeId"
    label="employeeId"
    reference="employees"
    alwaysOn
  />,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
  ,
];
